services:
  app:
    build: . 
    volumes:
      - .:/FAQ_Model
    ports:
    - 8000:8000
    image: "redis:alpine"
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
